#!/usr/bin/env bash
set -euo pipefail

# Invokes tsserver with a valid --npmLocation option.
#
# This wrapper is needed because there's currently no way to specify
# --npmLocation when invoking typescript-language-server.
#
# (We have to specify --npmLocation because by default, tsserver looks for an
# `npm` in the same location as `node`. Under Homebrew, _symlinks_ to node and
# npm live in the same directory (/usr/local/bin), but the actual binaries
# reside in separate directories.)
#
# See:
#  - https://github.com/theia-ide/typescript-language-server/issues/122
#  - https://github.com/microsoft/TypeScript/issues/23924#issuecomment-770261568

exec tsserver --npmLocation "$(which npm)" "$@"
